export const appLiterals = {
    btnSave: 'Guardar',
    btnCreate: 'Crear',
    btnCancel: 'Cancelar',
    btnDelete: 'Eliminar',
    btnEdit: 'Editar',
    btnBack: 'Volver',
    btnLogin: 'Iniciar sesión',
    btnRegister: 'Registrar usuario',
    editTitle: 'Editar',
    placeholderName: 'Nombre',
    selectImage: 'Seleccionar imagen',
    imageNotValid: 'Archivo no válido. La imagen tiene que ser formato JPEG o PNG.',
    selectCategory: 'Seleccionar Categoría',
    selectBrand: 'Seleccionar Marca',
    selectProvider: 'Seleccionar Proveedor',
    description: 'Descripción',
    labelCategory: 'Category',
    labelBrand: 'Marca',
    labelUnits: 'Unidades',
    labelPrice: 'Precio',
    labelTotal: 'Total',
    labelStock: 'Stock',
    brands: {
        brands: 'Marcas',
        createBrand: 'Crear Marca',
        registeredBrands: 'Marcas creadas',
        dataNotValidMsg: 'Dato no válido. Debe escribir una marca.',
        existingBrandMsg: 'La Marca ya existe.',
        cannotDeleteBrandMsg: 'No puede borrar la marca porque tiene productos existentes.',
        deleteBrandMsg: 'Desea eliminar la marca?',
        emptyBrandList: 'No se encontraron marcas creadas.'
    },
    category: {
        categories: 'Categorías',
        category: 'Categoría:',
        createCategory: 'Crear Categoría',
        registeredCategory: 'Categorías creadas',
        dataNotValidMsg: 'Dato no válido. Debe escribir una categoría.',
        existingCategoryMsg: 'La Categoría ya existe.',
        cannotDeleteBCategoryMsg: 'No puede borrar la categoría porque tiene productos existentes.',
        deleteCategoryMsg: 'Desea eliminar la categoría?',
        emptyCategoryList: 'No se encontraron categorías creadas.'
    },
    provider: {
        provider: 'Proveedor:',
        providers: 'Proveedores',
        createProvider: 'Crear Proveedor',
        registeredProviders: 'Proveedores creados',
        providerInfo: 'Información del Proveedor',
        dataNotValidMsg: 'Dato no válido. Debe escribir una categoría.',
        existingProviderMsg: 'El proveedor ya existe.',
        cannotDeleteProviderMsg: 'No puede borrar el proveedor porque tiene productos existentes.',
        deleteCategoryMsg: 'Desea eliminar el proveedor?',
        emptyProviderList: 'No se encontraron proveedores creados.'
    },
    product: {
        products: 'Productos',
        createProduct: 'Crear Producto',
        registeredProducts: 'Productos registrados',
        dataNotValidMsg: 'Dato no válido. Debe escribir una categoría.',
        existingProductMsg: 'El producto ya existe.',
        deleteProductMsg: 'Desea eliminar el producto?',
        productCode: 'Código de producto:',
        emptyProductList: 'No se encontraron productos creados.'
    },
    price: {
        price: 'Precios',
        createPrice: 'Crear Precios de Productos',
        registeredPrices: 'Precios registrados',
        mustInsertPricesMsg: 'Debe ingresar valores para Precio de Compra y Precio de Venta',
        buyPriceIncorrectMsg: 'Precio de Compra, valor incorrecto.',
        salePriceIncorrectMsg: 'Precio de Venta, valor incorrecto.',
        deletePriceMsg: 'Desea eliminar el precio?',
        purchasePriceShort: 'Compra:',
        salePriceShort: 'Venta:'
    },
    stock: {
        stock: 'Stock',
        stockTitle: 'Inventario',
        registeredStock: 'Stock registrado'
    },
    sales: {
        sales: 'Realizar Ventas',
        searchProductTitle: 'Buscar Producto',
        productsAddedTitle: 'Productos agregados al carrito',
        btnSell: 'Realizar Venta',
        priceUnit: 'Precio x U.',
        dataNotValidMsg: 'Dato no válido. Debe escribir un nombre o código de producto.',
        alreadyInScreen: 'El producto ya esta en pantalla',
        insuficientStockMsg: 'No tiene el stock suficiente para esa cantidad de unidades a vender',
        finalizeSellMsg: 'Desea concretar la Venta?',
        soldMsg: 'Se realizó la Venta y se actualizó el Stock',
        cancelSellMsg: 'Desea cancelar la venta?',
        zeroStockMsg: 'No se pueden agregar 0 unidades, escriba una cantidad.'
    },
    paginationTexts: {
        previous: 'Previa',
        next: 'Próxima',
        pagination: 'Paginación',
        page: 'Página',
        currentPage: 'Estas en la página'
    },
    user: {
        username: 'Nombre de usuario',
        email: 'Correo electrónico',
        profile: 'Página de perfil',
        password: 'Contraseña',
        account: 'Datos de la cuenta',
        name: 'Nombre y apellido',
        createdDate: 'Fecha de registración',
    },
    login: {
        loginTitle: 'Inicio de sesión',
        loginConfirmationMsg: 'Has iniciado sesión',
        logoutConfirmationMsg: 'Has cerrado sesión'
    },
    register: {
        registerTitle: 'Página de registración',
        registerSubtitle: 'Registrar usuario',
        registerConfirmationMsg: 'Ahora estás registrado y puedes iniciar sesión',
        useValidEmailMsg: 'Por favor use un correo electrónico válido',
        fillAllFieldsMsg: 'Todos los campos son requeridos',
    },
    menu: {
      login: 'Ingresar',
      profile: 'Perfil',
      register: 'Registrarse',
      logout: 'Salir',
      home: 'Inicio',
      brand: 'Marcas',
      category: 'Categorías',
      provider: 'Proveedores',
      product: 'Productos',
      price: 'Precios',
      stock: 'Inventario',
      sale: 'Ventas',
      statistic: 'Estadísticas'
    },
    home: {
        homeTitle: 'MEAN Sales',
        homeSubtitle: 'Bienvenido a mean sales!',
        freePlanTitle: 'Versión gratuita!',
        premiumPlanTitle: 'Versión Premium',
        goldPlanTitle: 'Versión Gold',
    }
};
